=== vishvas01/htmlbasics/xml/student_details.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="student_details">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="first_name" type="xs:string"/>
                                        <xs:element name="last_name" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="registration_number" type="xs:string"/>
                            <xs:element name="department" type="xs:string"/>
                            <xs:element name="address" type="xs:string"/>
                            <xs:element name="phone_number">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{3}-\d{4}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== vishvas01/htmlbasics/xml/student_details.xml
<?xml version="1.0" encoding="UTF-8"?>
<student_details xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="student_details.xsd">
    <student>
        <name>
            <first_name>rakesh</first_name>
            <last_name>sharma</last_name>
        </name>
        <registration_number>12345</registration_number>
        <department>Computer Science</department>
        <address>123 stark avenue</address>
        <phone_number>123-4567</phone_number>
    </student>
    <student>
        <name>
            <first_name>suresh</first_name>
            <last_name>verma</last_name>
        </name>
        <registration_number>67890</registration_number>
        <department>Mathematics</department>
        <address>456 pain hotel</address>
        <phone_number>987-6543</phone_number>
    </student>
</student_details>
